apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: cfut_r3uYbkv8UIzKfDl1LlDkIpWrSOms******************** # Use your API token from "cloudflare.com" where your domain name is hosted
